'use client';

import Link from 'next/link';

import { describeQuestion } from '@/lib/scoring';
import type { EvaluationResult, QuestionResult } from '@/lib/types';

const STATUS_STYLES: Record<QuestionResult['status'], string> = {
  correct: 'text-ok',
  wrong: 'text-bad',
  not_answered: 'text-muted',
  flagged: 'text-warn',
};

function Stat({ label, value, tone }: { label: string; value: string | number; tone?: string }) {
  return (
    <div className="rounded-lg border border-line px-4 py-3 print-break-inside-avoid">
      <dt className="text-xs uppercase tracking-wide text-muted">{label}</dt>
      <dd className={`mt-1 text-xl font-semibold tabular-nums ${tone ?? ''}`}>{value}</dd>
    </div>
  );
}

export default function ResultSheet({
  result,
  collegeName,
  evaluatedAt,
}: {
  result: EvaluationResult;
  collegeName?: string | null;
  evaluatedAt?: string | null;
}) {
  return (
    <div>
      <div className="no-print mb-6 flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-2xl font-bold tracking-tight">Result</h1>
        <div className="flex gap-2">
          <button onClick={() => window.print()} className="btn-primary">
            Download / print PDF
          </button>
          <Link href="/evaluate" className="btn-secondary">
            Evaluate another
          </Link>
        </div>
      </div>

      <div className="card print-plain">
        <header className="border-b border-line pb-4">
          <h2 className="text-xl font-semibold">{result.student_name}</h2>
          <p className="hint mt-1">
            {result.roll_number ? `Roll number ${result.roll_number}` : 'No roll number given'}
            {collegeName ? ` · ${collegeName}` : ''}
            {evaluatedAt ? ` · ${new Date(evaluatedAt).toLocaleString()}` : ''}
          </p>
        </header>

        <dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <Stat
            label="Total marks"
            value={`${result.total_marks} / ${result.max_marks}`}
            tone="text-brand"
          />
          <Stat label="Percentage" value={`${result.percentage.toFixed(2)}%`} />
          <Stat label="Correct" value={result.correct_count} tone="text-ok" />
          <Stat label="Wrong" value={result.wrong_count} tone="text-bad" />
        </dl>

        <p className="hint mt-3">
          {result.not_answered_count} not answered · {result.flagged_count} flagged for review
        </p>

        {!result.alignment.aligned && (
          <p className="alert-warn mt-4">
            This sheet could not be aligned to the template
            {result.alignment.reason ? ` (${result.alignment.reason})` : ''}, so it was scored
            from the photo as-is. Please double-check these marks by hand, and re-photograph
            the sheet flat and straight-on for a reliable read.
          </p>
        )}

        {result.flagged_count > 0 && (
          <p className="alert-warn mt-4">
            {result.flagged_count} question{result.flagged_count === 1 ? ' was' : 's were'}{' '}
            flagged — either more than one bubble was filled, or the marking was too faint to
            read confidently. Flagged questions are scored as wrong.
          </p>
        )}

        <section className="mt-8">
          <h3 className="font-semibold">Question by question</h3>
          <ul className="mt-3 grid gap-x-8 gap-y-0.5 sm:grid-cols-2 lg:grid-cols-3">
            {result.questions.map((q) => {
              const { icon, text } = describeQuestion(q);
              return (
                <li
                  key={q.q}
                  className="flex items-baseline gap-2 border-b border-line/60 py-1.5 text-sm print-break-inside-avoid"
                >
                  <span className="w-9 shrink-0 tabular-nums text-muted">Q{q.q}:</span>
                  <span className={`w-4 shrink-0 font-semibold ${STATUS_STYLES[q.status]}`}>
                    {icon}
                  </span>
                  <span className="min-w-0 flex-1 text-muted">{text}</span>
                  <span
                    className={`shrink-0 tabular-nums ${
                      q.marks > 0 ? 'text-ok' : q.marks < 0 ? 'text-bad' : 'text-muted'
                    }`}
                  >
                    {q.marks > 0 ? `+${q.marks}` : q.marks}
                  </span>
                </li>
              );
            })}
          </ul>
        </section>

        <footer className="mt-8 border-t border-line pt-4 text-xs text-muted">
          Marking scheme: +4 correct · 0 wrong · 0 not answered · −1 multiple bubbles · flagged
          questions scored as wrong. Generated by OMREval.
        </footer>
      </div>
    </div>
  );
}
